In [24]:
import pandas as pd

data = pd.read_csv('cardio_dataset-original.csv')

# Step 1 - Handling Outliers

In [28]:
factor = 4

upper_lim = data['AGEIR'].mean () + data['AGEIR'].std () * factor
lower_lim = data['AGEIR'].mean () - data['AGEIR'].std () * factor

data_new = data[(data['AGEIR'] < upper_lim) & (data['AGEIR'] > lower_lim)]

In [29]:
upper_lim = data_new['TC'].mean () + data_new['TC'].std () * factor
lower_lim = data_new['TC'].mean () - data_new['TC'].std () * factor

data_new = data_new[(data_new['TC'] < upper_lim) & (data_new['TC'] > lower_lim)]

In [30]:
upper_lim = data_new['HDL'].mean () + data_new['HDL'].std () * factor
lower_lim = data_new['HDL'].mean () - data_new['HDL'].std () * factor

data_new = data_new[(data_new['HDL'] < upper_lim) & (data_new['HDL'] > lower_lim)]

In [31]:
upper_lim = data_new['RISK'].mean () + data_new['RISK'].std () * factor
lower_lim = data_new['RISK'].mean () - data_new['RISK'].std () * factor

data_new = data_new[(data_new['RISK'] < upper_lim) & (data_new['RISK'] > lower_lim)]

In [15]:
data_new.reset_index()

      index     SEX  AGEIR   TC  HDL      SMOKE_       BPMED DIAB_noyes  RISK
0         0  female     48  236   66  no smoking      taking         no   1.1
1         1    male     48  260   51  no smoking      taking        yes   7.0
2         2    male     44  187   49     smoking      taking         no   7.0
3         3  female     42  216   57     smoking      taking         no   0.4
4         4  female     56  156   42  no smoking      taking         no   2.2
5         5    male     44  162   57     smoking      taking         no   3.0
6         6    male     50  244   47  no smoking      taking         no   4.2
7         7    male     48  212   30     smoking      taking         no  17.4
8         8  female     66  202   53  no smoking      taking        yes  13.4
9         9    male     63  186   46     smoking      taking         no  17.3
10       10    male     42  267   28     smoking      taking         no  19.8
11       11    male     58  234   36     smoking      taking         no  13.2
12       12    male     72  277   47  no smoking      taking         no  36.2
13       13  female     45  206   42     smoking      taking         no   2.9
14       14    male     69  249   62  no smoking      taking         no  11.7
15       15  female     63  205   47  no smoking      taking         no   4.3
16       16  female     41  218   81  no smoking      taking         no   0.3
17       17    male     55  194   36  no smoking      taking         no   9.7
18       18    male     72  228   44     smoking      taking        yes  38.1
19       19    male     55  216   35  no smoking      taking         no   9.3
20       20  female     65  175   78     smoking      taking         no   6.3
21       21    male     57  245   54     smoking  not taking         no  14.0
22       22  female     49  247   45     smoking      taking        yes   6.3
23       23    male     65  281   51  no smoking      taking         no  15.1
24       24  female     42  141   45  no smoking      taking         no   0.3
25       25  female     48  270   44  no smoking      taking        yes   3.5
26       26    male     43  212   67     smoking  not taking        yes  17.2
27       27    male     72  256   33  no smoking      taking         no  25.3
28       28    male     59  271   42  no smoking      taking         no   9.9
29       29    male     43  185   82  no smoking      taking         no   0.7
...     ...     ...    ...  ...  ...         ...         ...        ...   ...
6535   6613  female     73  225   50  no smoking  not taking         no  21.0
6536   6614    male     57  258   50  no smoking      taking         no   7.1
6537   6615  female     41  203   56  no smoking      taking         no   0.5
6538   6616    male     67  231   52  no smoking      taking         no  19.4
6539   6617  female     57  174   48  no smoking      taking         no   1.8
6540   6618    male     71  203   75     smoking      taking         no  21.2
6541   6619    male     43  150   26     smoking      taking         no   4.8
6542   6620    male     56  240   44     smoking      taking        yes  21.6
6543   6621    male     47  230   30  no smoking      taking        yes  12.0
6544   6622    male     40  223   36  no smoking      taking         no   2.1
6545   6623    male     62  185   53  no smoking      taking        yes  18.8
6546   6624    male     76  132   40     smoking      taking         no  25.4
6547   6625    male     71  217   86  no smoking      taking         no  15.5
6548   6626  female     62  163   62     smoking      taking         no  16.3
6549   6627  female     40  254   73  no smoking      taking         no   0.3
6550   6628  female     73  262   56  no smoking      taking         no  19.4
6551   6629    male     45  207   57  no smoking      taking         no   1.9
6552   6630  female     41  181   50  no smoking      taking         no   0.4
6553   6631  female     74  189   32     smoking  not taking        yes  52.8
6554   6632  female     45  308   40  no smoking      taking         no   1.7
6555   6633  female     41  243   50  no smoking      taking        yes   1.6
6556   6634    male     52  196   49  no smoking      taking         no   3.6
6557   6635  female     43  210   51  no smoking      taking         no   0.6
6558   6637  female     55  223   64  no smoking      taking         no   1.3
6559   6638  female     73  320   73  no smoking      taking         no  19.0
6560   6639  female     65  307   42     smoking  not taking        yes  36.6
6561   6640  female     42  169   56  no smoking  not taking         no   0.8
6562   6641    male     65  212   35     smoking  not taking         no  30.6
6563   6642    male     66  184   39  no smoking  not taking         no  23.8
6564   6643  female     45  203   51  no smoking      taking         no   1.0

[6565 rows x 9 columns]

# Step 2 - Scaling

In [32]:
numerical_data=data_new.drop(['SEX','SMOKE_','BPMED','DIAB_noyes','RISK'],axis=1)
numerical_data.head()

   AGEIR   TC  HDL
0     48  236   66
1     48  260   51
2     44  187   49
3     42  216   57
4     56  156   42

In [33]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
transformed_numerical_data = minmax_scaler.fit_transform(numerical_data)
transformed_numerical_data=pd.DataFrame(transformed_numerical_data, columns = ['AGEIR', 'TC', 'HDL'])

In [18]:
print(transformed_numerical_data.isnull().sum())

AGEIR    0
TC       0
HDL      0
dtype: int64

# Step 3 - Categorical Encoding

In [19]:
data_new["SEX"] = data_new["SEX"].astype('category')
data_new["SMOKE_"] = data_new["SMOKE_"].astype('category')
data_new["BPMED"] = data_new["BPMED"].astype('category')
data_new["DIAB_noyes"] = data_new["DIAB_noyes"].astype('category')
print(data_new.dtypes)

SEX           category
AGEIR            int64
TC               int64
HDL              int64
SMOKE_        category
BPMED         category
DIAB_noyes    category
RISK           float64
dtype: object

### 1 - Label Encoding

In [20]:
categorical_data = data_new.drop(['AGEIR', 'TC', 'HDL','RISK'], axis=1)
categorical_data.head()

      SEX      SMOKE_   BPMED DIAB_noyes
0  female  no smoking  taking         no
1    male  no smoking  taking        yes
2    male     smoking  taking         no
3  female     smoking  taking         no
4  female  no smoking  taking         no

In [21]:
categorical_data["SEX"] = categorical_data["SEX"].cat.codes
categorical_data["SMOKE_"] = categorical_data["SMOKE_"].cat.codes
categorical_data["BPMED"] = categorical_data["BPMED"].cat.codes
categorical_data["DIAB_noyes"] = categorical_data["DIAB_noyes"].cat.codes
categorical_data.head()

   SEX  SMOKE_  BPMED  DIAB_noyes
0    0       0      1           0
1    1       0      1           1
2    1       1      1           0
3    0       1      1           0
4    0       0      1           0

### 2- One Hot Encoding

categorical_data = data_new.drop(['AGEIR', 'TC', 'HDL','RISK'], axis=1)
categorical_data.head()

encoded_sex = pd.get_dummies(categorical_data['SEX'])
encoded_smoke = pd.get_dummies(categorical_data['SMOKE_'])
encoded_bpmed = pd.get_dummies(categorical_data['BPMED'])
encoded_diab = pd.get_dummies(categorical_data['DIAB_noyes'])


categorical_data=categorical_data.join(encoded_sex)
categorical_data=categorical_data.join(encoded_smoke)
categorical_data=categorical_data.join(encoded_bpmed)
categorical_data=categorical_data.join(encoded_diab)

categorical_data.head()

categorical_data=categorical_data.drop(['SEX','SMOKE_','BPMED','DIAB_noyes'],axis=1)
categorical_data.head()

# Step 4 -Reforming the dataset

In [22]:
dataset=categorical_data.join(transformed_numerical_data)
dataset=dataset.join(data_new['RISK'])
dataset.head()

   SEX  SMOKE_  BPMED  DIAB_noyes     AGEIR        TC       HDL  RISK
0    0       0      1           0  0.205128  0.531532  0.519231   1.1
1    1       0      1           1  0.205128  0.603604  0.375000   7.0
2    1       1      1           0  0.102564  0.384384  0.355769   7.0
3    0       1      1           0  0.051282  0.471471  0.432692   0.4
4    0       0      1           0  0.410256  0.291291  0.288462   2.2

In [165]:
dataset=dataset.dropna()

In [23]:
print(dataset.isnull().sum())

SEX            0
SMOKE_         0
BPMED          0
DIAB_noyes     0
AGEIR         77
TC            77
HDL           77
RISK           0
dtype: int64

# Step 5 - Training

In [ ]:
dataset=dataset.values() #numpy

data=dataset[:,:7]
target=dataset[:,7]